from typing import Optional

class Enr:
    @staticmethod
    def from_base64(text: str) -> "Enr": ...
    @staticmethod
    def from_bytes(data: bytes) -> "Enr": ...

    @property
    def seq(self) -> int: ...
    @property
    def node_id(self) -> bytes: ...
    @property
    def ip4(self) -> Optional[str]: ...
    @property
    def ip6(self) -> Optional[str]: ...
    @property
    def tcp4(self) -> Optional[int]: ...
    @property
    def tcp6(self) -> Optional[int]: ...
    @property
    def udp4(self) -> Optional[int]: ...
    @property
    def udp6(self) -> Optional[int]: ...
    @property
    def public_key(self) -> bytes: ...
    @property
    def identity_scheme(self) -> Optional[str]: ...

    def set_ip4(self, addr: str, key: "SigningKey") -> None: ...
    def set_ip6(self, addr: str, key: "SigningKey") -> None: ...
    def set_tcp4(self, port: int, key: "SigningKey") -> None: ...
    def set_tcp6(self, port: int, key: "SigningKey") -> None: ...
    def set_udp4(self, port: int, key: "SigningKey") -> None: ...
    def set_udp6(self, port: int, key: "SigningKey") -> None: ...
    def set_seq(self, seq: int, key: "SigningKey") -> None: ...
    def set(self, key: str, value: bytes, signing_key: "SigningKey") -> None: ...
    def get(self, key: str) -> Optional[bytes]: ...

    def to_base64(self) -> str: ...
    def to_bytes(self) -> bytes: ...

    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, bytes]]: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class SigningKey:
    @staticmethod
    def from_secp256k1(secret: bytes) -> "SigningKey": ...
    @staticmethod
    def from_ed25519(secret: bytes) -> "SigningKey": ...
    @staticmethod
    def generate_secp256k1() -> "SigningKey": ...
    @staticmethod
    def generate_ed25519() -> "SigningKey": ...

    def public_key(self) -> bytes: ...
    def builder(self) -> "EnrBuilder": ...

class EnrBuilder:
    def ip4(self, addr: str) -> None: ...
    def ip6(self, addr: str) -> None: ...
    def tcp4(self, port: int) -> None: ...
    def tcp6(self, port: int) -> None: ...
    def udp4(self, port: int) -> None: ...
    def udp6(self, port: int) -> None: ...
    def add(self, key: str, value: bytes) -> None: ...
    def build(self, key: "SigningKey") -> Enr: ...
